### LOCATOR ELEMENTS FOR SAUCE DEMO APPLICATION ###
emailuser=          "xpath=//*[@id='user-name']"
passworduser=       "xpath=//*[@id='password']"
homepage_login=     "xpath=//div[@class='login_logo']"
button_login=       "xpath=//*[@id='login-button']"
verify_login=       "xpath=//span[@class='title' and @data-test='title' and text()='Products']"
backpackitem=       "xpath=//button[@data-test='add-to-cart-sauce-labs-backpack']"
bikelight=          "xpath=//button[@data-test='add-to-cart-sauce-labs-bike-light']"
tshrirtitem=        "xpath=//button[@data-test='add-to-cart-sauce-labs-bolt-t-shirt']"
cartlink=           "xpath=//a[@data-test='shopping-cart-link']"
buttoncheckout=     "xpath=//button[@data-test='checkout']"
firstname=          "xpath=//*[@id='first-name']"
lastname=           "xpath=//*[@id='last-name']"
postalcodezip=      "xpath=//*[@id='postal-code']"
buttoncontinue=     "xpath=//*[@id='continue']"
buttonfinish=       "xpath=//*[@id='finish']"
verifycompletebuy=  "xpath=//h2[contains(text(), 'Thank you for your order')]"
buttonbackhome=     "xpath=//*[@id='back-to-products']"
homepageproducts=   "xpath=//span[@class='title' and @data-test='title' and text()='Products']"
deletebikelight=    "xpath=//*[@id='remove-sauce-labs-bike-light']"
errornotinputdata=  "xpath=//div[contains(@class, 'error-message-container')]//h3[@data-test='error']"