## varible appium lion parcel  ##
buttonsetuju=       'xpath=//android.widget.TextView[@resource-id="com.lionparcel.services.consumer:id/btnAgree"]'
buttonskip=         'xpath=//android.widget.TextView[@resource-id="com.lionparcel.services.consumer:id/txtSkip"]'
allowlocation=      'xpath=//android.widget.Button[@resource-id="com.android.permissioncontroller:id/permission_allow_foreground_only_button"]'
buttonx=            'xpath=//android.widget.ImageView[@resource-id="com.lionparcel.services.consumer:id/ivClose"]'
menu_cektarif=      'xpath=//android.widget.TextView[@resource-id="com.lionparcel.services.consumer:id/txtTitle" and @text="Cek Tarif"]'
home_cektarif=      'xpath=//android.widget.TextView[@text="Cek Tarif untuk Pengirimanmu"]'
origin_loc=         'xpath=//android.widget.EditText[@resource-id="com.lionparcel.services.consumer:id/edtOriginAddress"]'
input_origin=       'xpath=//android.widget.EditText[@resource-id="com.lionparcel.services.consumer:id/edtRouteSearch"]'
origin_routename=   'xpath=//android.widget.TextView[@resource-id="com.lionparcel.services.consumer:id/txtOriginRouteName"]'
destination_loc=    'xpath=//android.widget.EditText[@resource-id="com.lionparcel.services.consumer:id/edtDestinationAddress"]'
input_destination=  'xpath=//android.widget.EditText[@resource-id="com.lionparcel.services.consumer:id/edtRouteSearch"]'
destination_name=   'xpath=//android.widget.TextView[@resource-id="com.lionparcel.services.consumer:id/txtDistrictRouteName"]'
buttoncek_tarif=    'xpath=//android.widget.Button[@resource-id="com.lionparcel.services.consumer:id/btnCheckTariff"]'
input_beratbarang=  'xpath=//android.widget.EditText[@resource-id="com.lionparcel.services.consumer:id/edtTotalWeight"]'
panjang=            'xpath=//android.widget.EditText[@resource-id="com.lionparcel.services.consumer:id/edtDimensionLong"]'
lebar=              'xpath=//android.widget.EditText[@resource-id="com.lionparcel.services.consumer:id/edtDimensionWide"]'
tinggi=             'xpath=//android.widget.EditText[@resource-id="com.lionparcel.services.consumer:id/edtDimensionHeight"]'
jenisbarang=        'xpath=//android.widget.EditText[@resource-id="com.lionparcel.services.consumer:id/edtPackageType"]'
inputjenisbarang=   'xpath=//android.widget.EditText[@resource-id="com.lionparcel.services.consumer:id/edtCategorySearch"]'
pilihjenisbarang=   'xpath=//android.widget.TextView[@resource-id="com.lionparcel.services.consumer:id/txtCommodity" and @text="Elektronik & Gadget"]'
inputnilaibarang=   'xpath=//android.widget.EditText[@resource-id="com.lionparcel.services.consumer:id/edtInsurancePrice"]'
jenispengiriman=    'xpath=(//android.widget.ImageView[@content-desc="Ini merupakan sebuah gambar"])[7]'
checkboxassurance=  'xpath=//android.widget.CheckBox[@resource-id="com.lionparcel.services.consumer:id/cbInsurance"]'
nilaiasuransi=      'xpath=//android.widget.TextView[@resource-id="com.lionparcel.services.consumer:id/txtInsurance"]'
totalbiaya=         'xpath=//android.widget.TextView[@resource-id="com.lionparcel.services.consumer:id/txtTotalTariffEstimation"]'
requestpickup=      'xpath=//android.widget.Button[@resource-id="com.lionparcel.services.consumer:id/buttonPickUp"]'
buttonlanjutkan=    'xpath=//android.widget.Button[@resource-id="com.lionparcel.services.consumer:id/btnNext"]'
namapengirim=       'xpath=//android.widget.EditText[@resource-id="com.lionparcel.services.consumer:id/edtSenderName"]'
nopengirim=         'xpath=//android.widget.EditText[@resource-id="com.lionparcel.services.consumer:id/edtPhoneNumber"]'
buttonconfirm=      'xpath=//android.widget.Button[@resource-id="com.lionparcel.services.consumer:id/btnConfirmation"]'
alamat=             'xpath=//android.widget.EditText[@resource-id="com.lionparcel.services.consumer:id/edtWithMapsButton"]'
kecamatan=          'xpath=//android.widget.AutoCompleteTextView[@resource-id="com.lionparcel.services.consumer:id/edtDestination"]'
patokan=            'xpath=//android.widget.EditText[@resource-id="com.lionparcel.services.consumer:id/edtAddressOptional"]'
namapengguna=       'xpath=//android.widget.EditText[@resource-id="com.lionparcel.services.consumer:id/edtContent"]'
notelppengguna=     'xpath=//android.widget.EditText[@resource-id="com.lionparcel.services.consumer:id/edtPhoneNumber"]'
buttonlanjutkan3=   'xpath=//android.widget.Button[@resource-id="com.lionparcel.services.consumer:id/btnNext"]'
jenisbarangpilih=   'xpath=//android.widget.EditText[@resource-id="com.lionparcel.services.consumer:id/edtChooseCommodity"]'
inputjenisbarang2=  'xpath=//android.widget.EditText[@resource-id="com.lionparcel.services.consumer:id/edtCategorySearch"]'
jenisbarangchoose=  'xpath=(//android.view.ViewGroup[@resource-id="com.lionparcel.services.consumer:id/clContent"])[1]'
inputnilaibarang2=  'xpath=//android.widget.EditText[@resource-id="com.lionparcel.services.consumer:id/edtPriceField"]'
buttonlanjutkan2=   'xpath=//android.widget.Button[@resource-id="com.lionparcel.services.consumer:id/btnNext"]'
buttonpembayaran=   'xpath=//android.widget.Button[@resource-id="com.lionparcel.services.consumer:id/btnPay"]'
halamanbayar=       'xpath=//android.widget.TextView[@resource-id="com.lionparcel.services.consumer:id/txtTitle"]'
gopay=              'xpath=(//android.widget.ImageView[@content-desc="Ini merupakan sebuah gambar"])[5]'
buttonfinalbayar=   'xpath=//android.widget.Button[@resource-id="com.lionparcel.services.consumer:id/btnPay"]'
aplikasinotinstal=  'xpath=//android.widget.TextView[@resource-id="com.lionparcel.services.consumer:id/txtTitle"]'
tapatlocation=      'xpath=//android.view.ViewGroup[@resource-id="com.lionparcel.services.consumer:id/clLinkForm"]'
erortotalweight=    'xpath=//android.widget.TextView[@resource-id="com.lionparcel.services.consumer:id/textinput_helper_text"]'

